import 'core-js/stable';
import 'regenerator-runtime/runtime';
import './style/main.sass';
import './js/slider';
import './js/modal';
import './js/thanks';
import './js/setup-forms';
import './js/f5leads-init';
import './js/f5leads';
